# Generated by Django 3.2.16 on 2022-12-26 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20221226_1747'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='posts_follows_unique_relationships',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='author',
            new_name='following',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'following'), name='posts_follows_unique_relationships'),
        ),
    ]
